import React from 'react';
import { createRoot } from 'react-dom/client';
import Button from './button';
import { todoModel } from '../model/provider';

export function mount(domElementId) {
  // ID must match with the one generated by UI5 Framework
  const el = document.getElementById(domElementId);
  const root = createRoot(el);
  root.render(
    <Button
      text="Button"
      color="red"
      onClick={() => {
        todoModel.addTodo({
          userId: 15,
          id: 6,
          title: 'From react with love',
          description: 'This todo has been added using a react component button',
          completed: true,
        });
      }}
    />,
  );
  // Render your React component instead
}
